### ISSUE TITLE
Implement strafing

### ISSUE THREAD

**Issue by szapp** [szapp/GothicFreeAim#131]
UPDATE:

The core mechanics finally work. Thanks to @Siemekk for providing the missing idea. It has been independently implemented. Now strafing needs to be stabilized for special cases and for spell combat. Afterwards, only proper animations are missing.

 - [x] Implement core mechanism
 - [x] Create dummy animations
 - [x] Do not allow going left and right at the same time (restrict key presses)
 - [x] Check distance to neatest obstacle and stop movement if too close
 - [x] Fix Gothic bug, where "normal" strafing or sliding/falling(?) interrupts casting but keeps spell level
 - [x] Prevent going backwards and "normal" strafing after spell left hand
 - [x] Prevent shifting to nearest focus when pressing left/right (causes focus to flicker)
 - [x] Do not allow quick-casting of spells during Gothic default strafing
 - [x] Prevent strafing after having fallen and lying on the ground
 - [x] Implement alternative for Gothic 2 controls in spell combat
 - [x] Prevent sounds while standing and turning in spell combat (Gothic 2 controls)
 - [x] Treat special case in Gothic 2 controls when sneaking during spell combat
 - [x] Add animation modifiers for certain spells when casting
 - [x] Allow disabling aim movement from `config/settings.d`
 - [x] Send passive perception "observe intruder" (seems to be deprecated?)
 - [x] Receiving damage stops the movement (Gothic 1 only)
 - [x] Blend animation: e.g.: `oCAniCtrl_Human::StartAni(oCAniCtrl_Human, blendAni, targetAni);` or remember common offset and start animations with offset (continues animation where left off)
 - [x] **Finish animations**. Four each (front, left, front-left, back-left): **Iteration 1**
    - ~Bow T0, T1~ *iteration 1*
    - ~Bow T2~ *iteration 1*
    - ~Crossbow T0, T1~ *iteration 1*
    - ~Crossbow T2~ *iteration 1*
    - ~Magic~ *iteration 1*
    - ~Magic special casting variations~ *iteration 1*
 - [x] Include new functions in architecture diagram

_______________________________________

OLD ISSUE DESCRIPTION:

From what it looks like in the engine function ``oCAIHuman::BowMode``, strafing is disabled during aiming only by checking the state of the aiming button. Leveraging this if-condition, could make strafing while aiming possible, provided the aiming and strafing animations don't interfere with each other.

This should only be briefly tested before giving it more thought; this remains a low-priority idea for now.

UPDATE:
Let's give it another shot:

 - Figure out a way to prevent redrawing the bow
 - Hook in such a way that it also works with Gothic 1 controls
 - Test with dummy animation
 - If all of the above succeeded, contact someone to create nice looking animations

**Comment by szapp** [comment]
Okay, some tests have come this far:
Strafing can simply be injected into `oCAIHuman::BowMode`, resulting in fully functioning strafing while aiming. Of course, the bow is not maintaining the aiming animation, and when stopping to strafe the bow is drawn again.

What can be done now, is create an animation, in which the bow is drawn an centered (that is where the bow always is while aiming) while strafing and figuring out a way to prevent redrawing the bow after strafing. The latter is not guaranteed to work.

For me the risk-reward for this feature (risk being it might not work and trying wastes too much time) is not worth going deeper into it at this point. Here is what I have so far: injecting strafing into `ocAIHuman::BowMode` which successfully allows strafing while aiming (as described above):

```C++

const int oCAIHuman__BowMode_6962A4 = 6906532; //0x6962A4 // Hook length 6
HookEngineF(oCAIHuman__BowMode_6962A4, 6, strafeWhileAiming);

func void strafeWhileAiming() {
    var oCNpc her; her = Hlp_GetNpc(hero);

    // Call strafing function. It handles button presses and directions
    const int oCAIHuman__PC_Strafe = 6925440; //0x69AC80
    const int call = 0;
    var int herAIPtr; herAIPtr = her.human_ai;
    var int zero;
    var int ret;
    if (CALL_Begin(call)) {
        CALL_IntParam(_@(zero)); // Argument ignored by function
        CALL_PutRetValTo(_@(ret));
        CALL__thiscall(_@(herAIPtr), oCAIHuman__PC_Strafe);
        call = CALL_End();
    };

    // The return value specifies whether the player is currently strafing or not
    if (ret) {
        // Strafing now
        // Exchange animation or something like that (actually too late at this point)
        // her.anictrl._t_strafel = aniID; // zTModelAniID* 
    };
```

**Comment by szapp** [comment]
The above code has found its way into the scripts, but is commented out. It has been left in there, in case someone wants to finish this feature.

**Comment by szapp** [comment]
Let's give it another shot:

1. Figure out a way to prevent redrawing the bow
1. Hook in such a way that it also works with Gothic 1 controls
1. Test with dummy animation

If all of the above succeed, contact someone to create nice looking animations.

**Comment by Siemekk** [comment]
Suggestion :)
}void StopAni(oCNpc* pnpc, zSTRING ani)
{
	zCModel* model = pnpc->GetModel();
	if(model->IsAnimationActive(ani.Upper()))	
		model->StopAnimation(ani.Upper());
}

void PlayAni(oCNpc* pnpc, zSTRING ani)
{
	zCModel* model = pnpc->GetModel();
	if(!model->IsAnimationActive(ani.Upper()))
		model->StartAni(ani.Upper(), 0);	
}
In BowMode:
if(!model->IsAnimationActive("S_BOWAIM") //Bows
{
	if(KeyPress(KEY_A))
	{
		PlayAni(player, "AniMoveLeft");
	}
}
But in MDS "AniMove" Must have a higher priority from "S_BOWAIM".

**Comment by szapp** [comment]
Unfortunately, `0x6B6170 oCAniCtrl_Human::InterpolateCombineAni` seems to require to (re-)start its animation before any interpolation can occur. Consequently, the aiming animation **will** be restarted every time it is interrupted. Changing the layers (priority) of the animations did not change that.
I think it is time for me to stop trying.

**Comment by szapp** [comment]
See new issue description.
