### ISSUE TITLE
Gothic 1 port

### ISSUE THREAD

**Issue by szapp** [szapp/GothicFreeAim#134]
Progress (Branch [gothic1](/szapp/g2freeAim/tree/gothic1))

- [x]  Port ConsoleCommands to Gothic 1 (see [LeGo dev branch](https://app.assembla.com/spaces/lego2/subversion/commits/126))
- [x] Resolve parsing errors: The scripts are fully parsable without any problems
- [x] Find addresses (and hope that all functions are similar to Gothic 2). Proceed in this order, to fail ASAP (find out it does not work rather sooner than later)
  1. ✔ Mouse movement and disabled auto turning:
     - ✔ `mouseUpdate` == `sub_4D3D90_X` from LeGo
     - ✔ `Cursor_Ptr`
     - ✔ `Cursor_sX`
     - ✔ `Cursor_sY`
     - ✔ `oCAniCtrl_Human__Turn`
     - ✖ `oCNpc__TurnToEnemy_camCheck` -> ✔ `oCAIHuman__MagicMode_turnToTarget`
  1. ✔ Shooting projectiles in manual direction:
     - ✔ `oCAIArrow__SetupAIVob` + stack offsets (function arguments)
     - ✔ `zSinCosApprox`
     - ✔ `zCVob__GetRigidBody`
     - ✔ `zCRigidBody` class offsets
  1. ✔ Trace ray and focus collection:
     - ✔ `zCWorld__TraceRayNearestHit_Vob`
     - ✔ `zTTraceRayReport` class offsets
     - ✔ `zCArray_zCVob__IsInList`
     - ✔ `zCVob__TraceRay`
     - ✔ `oCNpc__SetFocusVob`
     - ✔ `oCNpc__SetEnemy`
  1. ✔ Aiming animation:
     - ✔ `oCAIHuman__BowMode_interpolateAim` + stack offsets (function arguments)
     - ✔ `oCNpc__GetAngles`
 - [x] When reaching here, free aiming itself should work, proceed with the remaining addresses in no particular order
   1. ✔ Finalize free aiming for ranged and magic combat:
      - ✔ `oCAIHuman__BowMode_shoot`
      - ✔ `oCAIHuman__BowMode_postInterpolate`
      - ✔ `oCAIArrow__ReportCollisionToAI_hit` + stack offsets
      - ✔ `oCNpc__OnDamage_Anim_getModel`
      - ✔ `oCAIHuman__PC_Strafe`
   1. ✔ Feature: Collisions:
      - ✖ `oCAIArrowBase__ReportCollisionToAI_collNpc` -> ✔ `oCAIArrow__ReportCollisionToAI_destroyPrj`
      - ✖ `oCAIArrowBase__ReportCollisionToAI_collVob` *(done differently in Gothic 1)*
      - ✖ `oCAIArrowBase__ReportCollisionToAI_collWld` *(done differently in Gothic 1)*
      - ✔ `oCAIArrow__CanThisCollideWith` + stack offsets
      - ✔ `zCTrigger__vtbl`
      - ✔ `oCTriggerScript__vtbl`
   1. ✔ Feature: Critical hits:
      - ✔ `oCAIArrow__ReportCollisionToAI_hitChc` + stack offsets
      - ✔ `oCNpc__GetModel`
      - ✔ `zCModel__SearchNode`
      - ✔ `zCModel__GetBBox3DNodeWorld`
      - ✔ `zCModel__GetNodePositionWorld`
   1. ✔ Feature: Reusable projectiles
      - ✔ `oCAIArrow__DoAI_rtn` + stack offsets
      - ✔ `oCItem__InitByScript`
      - ✔ `zCVob__SetAI`
      - ✔ `oCAIArrowBase__ReportCollisionToAI_hitNpc` + stack offsets
      - ✖ `oCAIArrowBase__ReportCollisionToAI_hitVob` *(not needed in Gothic 1)*
      - ✖ `oCAIArrowBase__ReportCollisionToAI_hitWld` *(not needed in Gothic 1)*
- [x] Resolve discrepancy between hit chance calculation (skill level (G2) versus dexterity (G1))
- [x] Replace attaching FX to the aim vob by Wld_PlayEffect (in Gothic 1, since it does not support `oCItem.effect`) or remove the trail strip PFX from the PFX file completely in Gothic 1. Attach the suffix _G2 to the other PFX file
- [x] Adjust critical hits for Gothic 1: The damage is doubled and, unlike in Gothic 2, allows exceeding the protection values of the target when a normal shot wouldn't (this is desired in Gothic 1 and already happening in its default damage calculation!)
- [x] Re-integrate `freeAimCriticalHitAutoAim()` into the core scripts for both Gothic 1 and Gothic 2 and return a different critical hit chance for Gothic 1 (e.g. `return Npc_GetTalentValue(hero, NPC_TALENT_BOW);`).
- [x] Find a better solution for the poly trail (visibility of projectile). The PFX looks terrible for Gothic 1.
- [x] Rework the controls (mouse movement) for Gothic 1. They are too squishy and inconsistent (sometimes fast, sometimes slow), especially recoil is affected.
- [x] Stuck projectiles are oddly positioned. Sometimes they are barely visible and not focusable (collectable) anymore (too deep in the wall) and sometimes the are floating in front of it. Why? This does not happen in Gothic 2.

**Comment by szapp** [comment]
Before anything, the console command package of LeGo needs to be ported. Two engine addresses need to be found.

Side note: For Gothic 1 compatibility, the Ikarus class oCNpc needs to be adjusted (in the Gothic 1 scripts):
```C++
oCNpc.name1 -> oCNpc.name_1
```

**Comment by szapp** [comment]
Progress:

 - ConsoleCommands implemented (see LeGo dev branch)
 - Resolved parsing errors: The scripts are fully parsable without any problems

Left to do:

 - Find addresses (and hope that all functions are similar to Gothic 2)
 - Resolve discrepancy between hit chance calculation (skill level (G2) versus dexterity (G1))

**Comment by CarnageMarkus** [comment]
Instead of `oCNpc.name1`, you can use offset, which in combination with `MEMINT_SwitchG1G2` and  makes sciritps compatible even with class differences...

**Comment by szapp** [comment]
Thanks, it is corrected in LeGo (see [revision 127](https://app.assembla.com/spaces/lego2/subversion/commits/127))

@CarnageMarkus Do you remember how you got the address for the cursor movement for Gothic 1 ([sub_4D3D90_X](https://app.assembla.com/spaces/lego2/subversion/source/HEAD/dev/EngineAdr_G1.d#ln98))? I am not sure if this address is correct. In Gothic 2 it is correct, but in Gothic 1 a hooked function is called way too often (approximately 100x per frame). This causes the game to freeze.

**Comment by szapp** [comment]
@CarnageMarkus The address 0x4C7F40 works better for me. I will test it with the cursor functionality and update it in the LeGo SVN if it works.

**Comment by szapp** [comment]
Gothic 1 does not make (consistent) use of the camera modes. Instead, for magic and ranged combat the normal camera mode is used. The free aiming camera mode is necessary to have the head of the player model not obstruct the reticle.
In order to fix this problem, the op code has to be overwritten at every position where the camera modes are set for magic and ranged combat. This will take a while.

**Comment by szapp** [comment]
Projectiles in Gothic 1 are destroyed on impact. There is no implementation of bouncing off. Consequently, there is a lot less possible with respect to collisions and collectable projectiles. Handling of the projectile AI (oCAIArrow) is quite different from Gothic 2, but might still be close enough to implement projectiles that are stuck in the surface. If that is not possible, the collectable projectile feature will not be implemented in Gothic 1.

**Comment by szapp** [comment]
The provisional trial strip for Gothic 1 (PFX) is not very pretty and has to be improved.

**Comment by szapp** [comment]
Adjust recoil for Gothic 1. The mouse movement is of different speed. The recoil impact needs to be generally higher,

**Comment by szapp** [comment]
The mouse is very squishy in Gothic 1: The camera keeps on moving when the mouse already stopped, and eases into the new position. This should be fixed to have more responsive aiming.
