### ISSUE TITLE
Large bounding boxes decrease hit difficulty

### ISSUE THREAD

**Issue by szapp** [szapp/GothicFreeAim#159]
Hit detection is done, as by any other means of collision detection for dynamical objects, by bounding box. This is a problem for projectile collision detection since bounding boxes are quite large for a lot of NPC models (e.g. lurkers).

Alternatively performing collision checks by model (trace ray) comes down to a trace ray with the vob which only works by bounding box detection (for dynamical objects) - which essentially is the same. Another approach, besides increasing `GFA_SCATTER_MISS` (which will increase the number of misses while leaving the number of hits untouched) is to hook `oCAIArrow::CanThisCollideWith` and add the respective NPC to the ignore list if the trajectory of the projectile won't be within the range of `Gil_Values.FIGHT_RANGE_BASE[GUILD]` from `Bip01`, where `GUILD` is the NPC guild ID. However, this might be too strict.

**Comment by szapp** [comment]
## Another idea

### Background
For positive hits of projectiles with NPCs, Gothic only performs rough collision detection by bounding boxes. A positive rough collision detection is reported and can be refined in `oCAIArrow::CanThisCollideWith`. In this function a ray could be casted from the projectiles position (which should be at the edge of the bounding box of the NPC at that moment) in the direction of the projectile trajectory.

### Problem
As mentioned above, a ray can detect dynamical objects (such as NPCs) only with the bounding box flag enabled. A ray with bounding box flag is the source of the hit detection problem, as the bounding box is too large.

### Possible Solution
If the criteria for a non-bounding box ray is that the object has be non-dynamical, the NPC could be frozen during the ray and unfrozen afterwards. This should make the NPC's model identical to that of a normal vob, allowing a ray without the bounding box flag.

### Risks
This is purely speculation, and even if it works the question remains whether the freezing leaves visible traces.

### Technicalities
Freezing the NPC might be possible by changing either one of these properties (`zCVob.bitfield`):
- `sleepingMode`
- `collDetectionDynamic`
- `isInMovementMode`
- `physicsEnabled`

### Next Steps
To verify this assumption, a few steps will be taken (in chronological order)
- [ ] Compare the bitfields of vobs and NPCs to determine which makes the difference with respect to being dynamic.
- [ ] Verify that differentiation by drawing the bounding boxes of NPCs and vobs in the world and comparing their color (weak verification).
- [ ] With a frame function or similar, cast a ray (without bounding box flag) from the camera in viewing direction and visualize the intersection as done in GFA with `GFA_VisualizeTraceRay()`.
- [ ] If the ray positively intersects with the NPC without bounding box flag, investigate what happens if briefly changing the above identified property impacts ongoing animations or leaves any other visible traces.
- [ ] If all of the above work, implement it in `oCAIArrow::CanThisCollideWith` and verify that it works without drawbacks.
- [ ] Optimize this secondary collision detection in `oCAIArrow::CanThisCollideWith`, such that it is only performed once for each projectile-NPC-combination. E.g. by adding the NPC to the ignore vob list of the projectile, if the check failed, to skip the check in any consecutive calls of `oCAIArrow::CanThisCollideWith`.

**Comment by szapp** [comment]
Reason for the different behavior with trace rays was not the bit field of the vob, but the underlying visual (`zCVob.visual`). For NPCs the visual is a zCModel, of which the trace ray is disabled if its class variable array `zCModels.skins_` holds a non-zero number of `zCMeshSoftSkin`.
When overwriting this condition and starting the trace ray **without** `zTRACERAY_FIRSTHIT`, the desired effect is achieved.

Why this condition is there in the first place might have very good reason and it should be kept in mind should bugs arise.

**Comment by szapp** [comment]
It works; only needs to be implemented properly.

**Comment by nicodex** [comment]
It seems that the meshSoftSkinList.GetNum() check in zCModel::TraceRay has been added as a hack during the development (and has never been removed). In fact this disables all TraceRay checks for all models with soft skins. Removing this hack permanently might result in performance issues (all soft skins with all their nodes are tested if zTRACERAY_FIRSTHIT is not set and an intersection with a node visual has been detected) and changed game behavior. Therefore the check might be disabled temporarily for your next TraceRay call, or (to avoid code segment changes) the soft skin count might be temporarily set to 0 (disable soft skin test and only do node checks).

**Comment by szapp** [comment]
Thanks for all the explanations. It seems to be the other way around, though. If I temporarily overwrite the (first only) soft skin check in `zCModel::TraceRay`, the trace ray performs as desired. If I instead temporarily change the number of soft skins to zero, the check is also passed. However, there are subsequent checks that require a positive number of soft skins for the trace ray to work (it seems).

So for now, I used the first approach and it works well for both Gothic 1 and Gothic 2.

I will edit this comment with a link to the final code, once I committed it.

**Comment by szapp** [comment]
### False Negatives
Sometimes projectiles fly through an NPC, if the NPC is moving. Presumably, this happens because the refined collision detection (model trace ray) is **only performed the first time** the projectile collides with the NPC's bounding box. Afterwards the NPC is put into the ignore list of the projectile, to not perform this check again and to increase performance. For NPCs with large bounding boxes (big distance from bounding box edge to model) the projectile trajectory might penetrate the model after a previous check has been negative, because the NPC is moving while the projectile flies through be bounding box.

A simple solution would be not to put the NPC in the ignore list. However, the performance impact might be high (hooking `oCAIArrow::CanThisCollideWith` and casting a ray every frame while the projectile is inside the NPC's bounding box).

**Comment by szapp** [comment]
### False Negatives
Sometimes projectiles fly through an NPC, if the NPC is moving. Presumably, this happens because the refined collision detection (model trace ray) is **only performed the first time** the projectile collides with the NPC's bounding box. Afterwards the NPC is put into the ignore list of the projectile, to not perform this check again and to increase performance. For NPCs with large bounding boxes (big distance from bounding box edge to model) the projectile trajectory might penetrate the model after a previous check has been negative, because the NPC is moving while the projectile flies through be bounding box.

A simple solution would be not to put the NPC in the ignore list. However, the performance impact might be high (hooking `oCAIArrow::CanThisCollideWith` and casting a ray every frame while the projectile is inside the NPC's bounding box).
