### ISSUE TITLE
[Returning 2.0] Game crashes after intros while using Ninja GFA patch

### ISSUE THREAD

**Issue by asasyn134** [szapp/GothicFreeAim#196]
Hello,
I wanted to use GFA patch with Returning 2.0 ver 66,2. 
After loading the game's two intros game crashes and I'm getting error shown bellow.
![błąd](https://user-images.githubusercontent.com/23174586/55273649-7d462380-52ce-11e9-9391-6fe3532a0616.png)

On the other hand bloodsplatter patch is working correctly

**Comment by szapp** [comment]
Thank you for the report.

This issue has been fixed already for a while, but the patch was never updated. It is expected to be updated in roughly three weeks (Mid-April).

**Comment by asasyn134** [comment]
Thanks for the answer. 3 weeks is a long time tho :/ 
Is it that complicated or you do not have time for it?
